// Autogenerated C++ message buffer code.
// Source: clad/cloud/mic.clad
// Full command line: victor-clad/tools/message-buffers/emitters/CPP_emitter.py --output-union-helper-constructors --output-json -C src -I clad/src lib/util/source/anki/clad robot/clad/src coretech/vision/clad_src coretech/common/clad_src -o generated/clad/engine clad/cloud/mic.clad

#ifndef __CLAD_CLOUD_MIC_TAG_H__
#define __CLAD_CLOUD_MIC_TAG_H__

#include <functional>

namespace Anki {

namespace Vector {

namespace CloudMic {

enum class MessageTag : uint8_t {
  hotword,                // 0
  audio,                  // 1
  audioDone,              // 2
  connectionCheck,        // 3
  stopSignal,             // 4
  testStarted,            // 5
  streamTimeout,          // 6
  connectionResult,       // 7
  debugFile,              // 8
  result,                 // 9
  error,                  // 10
  streamOpen,             // 11
  INVALID           = 255
};

const char* MessageTagToString(const MessageTag tag);

} // namespace CloudMic

} // namespace Vector

} // namespace Anki

template<>
struct std::hash<Anki::Vector::CloudMic::MessageTag>
{
  size_t operator()(Anki::Vector::CloudMic::MessageTag t) const
  {
    return static_cast<std::underlying_type<Anki::Vector::CloudMic::MessageTag>::type>(t);
  }
};

#endif // __CLAD_CLOUD_MIC_TAG_H__
