// Autogenerated C++ message buffer code.
// Source: clad/cloud/mic.clad
// Full command line: victor-clad/tools/message-buffers/emitters/CPP_emitter.py --output-union-helper-constructors --output-json -C src -I clad/src lib/util/source/anki/clad robot/clad/src coretech/vision/clad_src coretech/common/clad_src -o generated/clad/engine clad/cloud/mic.clad

#ifndef __CLAD_CLOUD_MIC_H__
#define __CLAD_CLOUD_MIC_H__

#include <CLAD/SafeMessageBuffer.h>
#include <array>
#include <cassert>
#include <cstdint>
#include <string>
#include <vector>

#include "clad/cloud/micTag.h"
#include "json/json.h"

#include "clad/cloud/common.h"

namespace Anki {

namespace Vector {

namespace CloudMic {

#ifndef CLAD_CPP_WARN_UNUSED_RESULT
#define CLAD_CPP_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#endif

// ENUM StreamType
enum class StreamType : uint8_t {
  Normal         = 0,
  Blackjack      = 1,
  KnowledgeGraph = 2,
};

const char* EnumToString(const StreamType m);
inline const char* StreamTypeToString(const StreamType m) { return EnumToString(m); }

template<typename T>
CLAD_CPP_WARN_UNUSED_RESULT bool EnumFromString(const std::string& str, T& enumOutput);
CLAD_CPP_WARN_UNUSED_RESULT bool StreamTypeFromString(const std::string& str, StreamType& enumOutput);

StreamType StreamTypeFromString(const std::string&);

extern const char* StreamTypeVersionHashStr;
extern const uint8_t StreamTypeVersionHash[16];

constexpr uint8_t StreamTypeNumEntries = 3;

#ifndef CLAD_CPP_WARN_UNUSED_RESULT
#define CLAD_CPP_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#endif

// ENUM ErrorType
enum class ErrorType : uint8_t {
  Server        = 0,
  Timeout       = 1,
  Json          = 2,
  InvalidConfig = 3,
  Connecting    = 4,
  NewStream     = 5,
  Token         = 6,
  TLS           = 7,
  Connectivity  = 8,
};

const char* EnumToString(const ErrorType m);
inline const char* ErrorTypeToString(const ErrorType m) { return EnumToString(m); }

template<typename T>
CLAD_CPP_WARN_UNUSED_RESULT bool EnumFromString(const std::string& str, T& enumOutput);
CLAD_CPP_WARN_UNUSED_RESULT bool ErrorTypeFromString(const std::string& str, ErrorType& enumOutput);

ErrorType ErrorTypeFromString(const std::string&);

extern const char* ErrorTypeVersionHashStr;
extern const uint8_t ErrorTypeVersionHash[16];

constexpr uint8_t ErrorTypeNumEntries = 9;

#ifndef CLAD_CPP_WARN_UNUSED_RESULT
#define CLAD_CPP_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#endif

// ENUM ConnectionCode
enum class ConnectionCode : uint8_t {
  Available    = 0,
  Connectivity = 1,
  Tls          = 2,
  Auth         = 3,
  Bandwidth    = 4,
};

const char* EnumToString(const ConnectionCode m);
inline const char* ConnectionCodeToString(const ConnectionCode m) { return EnumToString(m); }

template<typename T>
CLAD_CPP_WARN_UNUSED_RESULT bool EnumFromString(const std::string& str, T& enumOutput);
CLAD_CPP_WARN_UNUSED_RESULT bool ConnectionCodeFromString(const std::string& str, ConnectionCode& enumOutput);

ConnectionCode ConnectionCodeFromString(const std::string&);

extern const char* ConnectionCodeVersionHashStr;
extern const uint8_t ConnectionCodeVersionHash[16];

constexpr uint8_t ConnectionCodeNumEntries = 5;

// STRUCTURE StreamOpen
struct StreamOpen
{
  std::string session;
  
  /**** Constructors ****/
  StreamOpen() = default;
  StreamOpen(const StreamOpen& other) = default;
  StreamOpen(StreamOpen& other) = default;
  StreamOpen(StreamOpen&& other) noexcept = default;
  StreamOpen& operator=(const StreamOpen& other) = default;
  StreamOpen& operator=(StreamOpen&& other) = default;
  
  explicit StreamOpen(const std::string& session)
  : session(session)
  {}
  
  explicit StreamOpen(const uint8_t* buff, size_t len);
  explicit StreamOpen(const CLAD::SafeMessageBuffer& buffer);
  
  /**** Pack ****/
  size_t Pack(uint8_t* buff, size_t len) const;
  size_t Pack(CLAD::SafeMessageBuffer& buffer) const;
  
  /**** Unpack ****/
  size_t Unpack(const uint8_t* buff, const size_t len);
  size_t Unpack(const CLAD::SafeMessageBuffer& buffer);
  
  size_t Size() const;
  
  bool operator==(const StreamOpen& other) const;
  bool operator!=(const StreamOpen& other) const;
  
  template <typename Callable>
  void Invoke(Callable&& func) const {
     func(session);
  }
  /**** JSON ****/
  Json::Value GetJSON() const;
  bool SetFromJSON(const Json::Value& json);
  
};

extern const char* StreamOpenVersionHashStr;
extern const uint8_t StreamOpenVersionHash[16];

// STRUCTURE Hotword
struct Hotword
{
  Anki::Vector::CloudMic::StreamType mode;
  std::string locale;
  std::string timezone;
  bool noLogging;
  
  /**** Constructors ****/
  Hotword() = default;
  Hotword(const Hotword& other) = default;
  Hotword(Hotword& other) = default;
  Hotword(Hotword&& other) noexcept = default;
  Hotword& operator=(const Hotword& other) = default;
  Hotword& operator=(Hotword&& other) = default;
  
  explicit Hotword(Anki::Vector::CloudMic::StreamType mode,
    const std::string& locale,
    const std::string& timezone,
    bool noLogging)
  : mode(mode)
  , locale(locale)
  , timezone(timezone)
  , noLogging(noLogging)
  {}
  
  explicit Hotword(const uint8_t* buff, size_t len);
  explicit Hotword(const CLAD::SafeMessageBuffer& buffer);
  
  /**** Pack ****/
  size_t Pack(uint8_t* buff, size_t len) const;
  size_t Pack(CLAD::SafeMessageBuffer& buffer) const;
  
  /**** Unpack ****/
  size_t Unpack(const uint8_t* buff, const size_t len);
  size_t Unpack(const CLAD::SafeMessageBuffer& buffer);
  
  size_t Size() const;
  
  bool operator==(const Hotword& other) const;
  bool operator!=(const Hotword& other) const;
  
  template <typename Callable>
  void Invoke(Callable&& func) const {
     func(mode, locale, timezone, noLogging);
  }
  /**** JSON ****/
  Json::Value GetJSON() const;
  bool SetFromJSON(const Json::Value& json);
  
};

extern const char* HotwordVersionHashStr;
extern const uint8_t HotwordVersionHash[16];

// STRUCTURE Filename
struct Filename
{
  std::string file;
  
  /**** Constructors ****/
  Filename() = default;
  Filename(const Filename& other) = default;
  Filename(Filename& other) = default;
  Filename(Filename&& other) noexcept = default;
  Filename& operator=(const Filename& other) = default;
  Filename& operator=(Filename&& other) = default;
  
  explicit Filename(const std::string& file)
  : file(file)
  {}
  
  explicit Filename(const uint8_t* buff, size_t len);
  explicit Filename(const CLAD::SafeMessageBuffer& buffer);
  
  /**** Pack ****/
  size_t Pack(uint8_t* buff, size_t len) const;
  size_t Pack(CLAD::SafeMessageBuffer& buffer) const;
  
  /**** Unpack ****/
  size_t Unpack(const uint8_t* buff, const size_t len);
  size_t Unpack(const CLAD::SafeMessageBuffer& buffer);
  
  size_t Size() const;
  
  bool operator==(const Filename& other) const;
  bool operator!=(const Filename& other) const;
  
  template <typename Callable>
  void Invoke(Callable&& func) const {
     func(file);
  }
  /**** JSON ****/
  Json::Value GetJSON() const;
  bool SetFromJSON(const Json::Value& json);
  
};

extern const char* FilenameVersionHashStr;
extern const uint8_t FilenameVersionHash[16];

// STRUCTURE AudioData
struct AudioData
{
  std::vector<int16_t> data;
  
  /**** Constructors ****/
  AudioData() = default;
  AudioData(const AudioData& other) = default;
  AudioData(AudioData& other) = default;
  AudioData(AudioData&& other) noexcept = default;
  AudioData& operator=(const AudioData& other) = default;
  AudioData& operator=(AudioData&& other) = default;
  
  explicit AudioData(const std::vector<int16_t>& data)
  : data(data)
  {}
  
  explicit AudioData(const uint8_t* buff, size_t len);
  explicit AudioData(const CLAD::SafeMessageBuffer& buffer);
  
  /**** Pack ****/
  size_t Pack(uint8_t* buff, size_t len) const;
  size_t Pack(CLAD::SafeMessageBuffer& buffer) const;
  
  /**** Unpack ****/
  size_t Unpack(const uint8_t* buff, const size_t len);
  size_t Unpack(const CLAD::SafeMessageBuffer& buffer);
  
  size_t Size() const;
  
  bool operator==(const AudioData& other) const;
  bool operator!=(const AudioData& other) const;
  
  template <typename Callable>
  void Invoke(Callable&& func) const {
     func(data);
  }
  /**** JSON ****/
  Json::Value GetJSON() const;
  bool SetFromJSON(const Json::Value& json);
  
};

extern const char* AudioDataVersionHashStr;
extern const uint8_t AudioDataVersionHash[16];

// STRUCTURE IntentResult
struct IntentResult
{
  std::string intent;
  std::string parameters;
  std::string metadata;
  
  /**** Constructors ****/
  IntentResult() = default;
  IntentResult(const IntentResult& other) = default;
  IntentResult(IntentResult& other) = default;
  IntentResult(IntentResult&& other) noexcept = default;
  IntentResult& operator=(const IntentResult& other) = default;
  IntentResult& operator=(IntentResult&& other) = default;
  
  explicit IntentResult(const std::string& intent,
    const std::string& parameters,
    const std::string& metadata)
  : intent(intent)
  , parameters(parameters)
  , metadata(metadata)
  {}
  
  explicit IntentResult(const uint8_t* buff, size_t len);
  explicit IntentResult(const CLAD::SafeMessageBuffer& buffer);
  
  /**** Pack ****/
  size_t Pack(uint8_t* buff, size_t len) const;
  size_t Pack(CLAD::SafeMessageBuffer& buffer) const;
  
  /**** Unpack ****/
  size_t Unpack(const uint8_t* buff, const size_t len);
  size_t Unpack(const CLAD::SafeMessageBuffer& buffer);
  
  size_t Size() const;
  
  bool operator==(const IntentResult& other) const;
  bool operator!=(const IntentResult& other) const;
  
  template <typename Callable>
  void Invoke(Callable&& func) const {
     func(intent, parameters, metadata);
  }
  /**** JSON ****/
  Json::Value GetJSON() const;
  bool SetFromJSON(const Json::Value& json);
  
};

extern const char* IntentResultVersionHashStr;
extern const uint8_t IntentResultVersionHash[16];

// STRUCTURE IntentError
struct IntentError
{
  Anki::Vector::CloudMic::ErrorType error;
  std::string extra;
  
  /**** Constructors ****/
  IntentError() = default;
  IntentError(const IntentError& other) = default;
  IntentError(IntentError& other) = default;
  IntentError(IntentError&& other) noexcept = default;
  IntentError& operator=(const IntentError& other) = default;
  IntentError& operator=(IntentError&& other) = default;
  
  explicit IntentError(Anki::Vector::CloudMic::ErrorType error,
    const std::string& extra)
  : error(error)
  , extra(extra)
  {}
  
  explicit IntentError(const uint8_t* buff, size_t len);
  explicit IntentError(const CLAD::SafeMessageBuffer& buffer);
  
  /**** Pack ****/
  size_t Pack(uint8_t* buff, size_t len) const;
  size_t Pack(CLAD::SafeMessageBuffer& buffer) const;
  
  /**** Unpack ****/
  size_t Unpack(const uint8_t* buff, const size_t len);
  size_t Unpack(const CLAD::SafeMessageBuffer& buffer);
  
  size_t Size() const;
  
  bool operator==(const IntentError& other) const;
  bool operator!=(const IntentError& other) const;
  
  template <typename Callable>
  void Invoke(Callable&& func) const {
     func(error, extra);
  }
  /**** JSON ****/
  Json::Value GetJSON() const;
  bool SetFromJSON(const Json::Value& json);
  
};

extern const char* IntentErrorVersionHashStr;
extern const uint8_t IntentErrorVersionHash[16];

// STRUCTURE ConnectionResult
struct ConnectionResult
{
  Anki::Vector::CloudMic::ConnectionCode code;
  std::string status;
  uint8_t numPackets;
  uint8_t expectedPackets;
  
  /**** Constructors ****/
  ConnectionResult() = default;
  ConnectionResult(const ConnectionResult& other) = default;
  ConnectionResult(ConnectionResult& other) = default;
  ConnectionResult(ConnectionResult&& other) noexcept = default;
  ConnectionResult& operator=(const ConnectionResult& other) = default;
  ConnectionResult& operator=(ConnectionResult&& other) = default;
  
  explicit ConnectionResult(Anki::Vector::CloudMic::ConnectionCode code,
    const std::string& status,
    uint8_t numPackets,
    uint8_t expectedPackets)
  : code(code)
  , status(status)
  , numPackets(numPackets)
  , expectedPackets(expectedPackets)
  {}
  
  explicit ConnectionResult(const uint8_t* buff, size_t len);
  explicit ConnectionResult(const CLAD::SafeMessageBuffer& buffer);
  
  /**** Pack ****/
  size_t Pack(uint8_t* buff, size_t len) const;
  size_t Pack(CLAD::SafeMessageBuffer& buffer) const;
  
  /**** Unpack ****/
  size_t Unpack(const uint8_t* buff, const size_t len);
  size_t Unpack(const CLAD::SafeMessageBuffer& buffer);
  
  size_t Size() const;
  
  bool operator==(const ConnectionResult& other) const;
  bool operator!=(const ConnectionResult& other) const;
  
  template <typename Callable>
  void Invoke(Callable&& func) const {
     func(code, status, numPackets, expectedPackets);
  }
  /**** JSON ****/
  Json::Value GetJSON() const;
  bool SetFromJSON(const Json::Value& json);
  
};

extern const char* ConnectionResultVersionHashStr;
extern const uint8_t ConnectionResultVersionHash[16];

// "Lookup Tables" for getting type by tag using template specializations
template<MessageTag tag>
struct Message_TagToType;

template<>
struct Message_TagToType<MessageTag::hotword> {
  using type = Anki::Vector::CloudMic::Hotword;
};
template<>
struct Message_TagToType<MessageTag::audio> {
  using type = Anki::Vector::CloudMic::AudioData;
};
template<>
struct Message_TagToType<MessageTag::audioDone> {
  using type = Anki::Vector::Void;
};
template<>
struct Message_TagToType<MessageTag::connectionCheck> {
  using type = Anki::Vector::Void;
};
template<>
struct Message_TagToType<MessageTag::stopSignal> {
  using type = Anki::Vector::Void;
};
template<>
struct Message_TagToType<MessageTag::testStarted> {
  using type = Anki::Vector::Void;
};
template<>
struct Message_TagToType<MessageTag::streamTimeout> {
  using type = Anki::Vector::Void;
};
template<>
struct Message_TagToType<MessageTag::connectionResult> {
  using type = Anki::Vector::CloudMic::ConnectionResult;
};
template<>
struct Message_TagToType<MessageTag::debugFile> {
  using type = Anki::Vector::CloudMic::Filename;
};
template<>
struct Message_TagToType<MessageTag::result> {
  using type = Anki::Vector::CloudMic::IntentResult;
};
template<>
struct Message_TagToType<MessageTag::error> {
  using type = Anki::Vector::CloudMic::IntentError;
};
template<>
struct Message_TagToType<MessageTag::streamOpen> {
  using type = Anki::Vector::CloudMic::StreamOpen;
};

// UNION Message
class Message
{
public:
  using Tag = MessageTag;
  /**** Constructors ****/
  Message() :_tag(Tag::INVALID) { }
  explicit Message(const CLAD::SafeMessageBuffer& buff);
  explicit Message(const uint8_t* buffer, size_t length);
  Message(const Message& other);
  Message(Message&& other) noexcept;
  Message& operator=(const Message& other);
  Message& operator=(Message&& other) noexcept;
  
  ~Message() { ClearCurrent(); }
  Tag GetTag() const { return _tag; }
  
  // Templated getter for union members by type
  // NOTE: Always returns a reference, even for trivial types, unlike untemplated version
  template<Tag tag>
  const typename Message_TagToType<tag>::type & Get_() const;
  
  // Templated creator for making a union object out of one if its members
  template <Tag tag>
  static Message Create_(typename Message_TagToType<tag>::type member);
  
  /** hotword **/
  static Message Createhotword(Anki::Vector::CloudMic::Hotword&& new_hotword);
  explicit Message(Anki::Vector::CloudMic::Hotword&& new_hotword);
  const Anki::Vector::CloudMic::Hotword& Get_hotword() const;
  void Set_hotword(const Anki::Vector::CloudMic::Hotword& new_hotword);
  void Set_hotword(Anki::Vector::CloudMic::Hotword&& new_hotword);
  
  /** audio **/
  static Message Createaudio(Anki::Vector::CloudMic::AudioData&& new_audio);
  explicit Message(Anki::Vector::CloudMic::AudioData&& new_audio);
  const Anki::Vector::CloudMic::AudioData& Get_audio() const;
  void Set_audio(const Anki::Vector::CloudMic::AudioData& new_audio);
  void Set_audio(Anki::Vector::CloudMic::AudioData&& new_audio);
  
  /** audioDone **/
  static Message CreateaudioDone(Anki::Vector::Void&& new_audioDone);
  const Anki::Vector::Void& Get_audioDone() const;
  void Set_audioDone(const Anki::Vector::Void& new_audioDone);
  void Set_audioDone(Anki::Vector::Void&& new_audioDone);
  
  /** connectionCheck **/
  static Message CreateconnectionCheck(Anki::Vector::Void&& new_connectionCheck);
  const Anki::Vector::Void& Get_connectionCheck() const;
  void Set_connectionCheck(const Anki::Vector::Void& new_connectionCheck);
  void Set_connectionCheck(Anki::Vector::Void&& new_connectionCheck);
  
  /** stopSignal **/
  static Message CreatestopSignal(Anki::Vector::Void&& new_stopSignal);
  const Anki::Vector::Void& Get_stopSignal() const;
  void Set_stopSignal(const Anki::Vector::Void& new_stopSignal);
  void Set_stopSignal(Anki::Vector::Void&& new_stopSignal);
  
  /** testStarted **/
  static Message CreatetestStarted(Anki::Vector::Void&& new_testStarted);
  const Anki::Vector::Void& Get_testStarted() const;
  void Set_testStarted(const Anki::Vector::Void& new_testStarted);
  void Set_testStarted(Anki::Vector::Void&& new_testStarted);
  
  /** streamTimeout **/
  static Message CreatestreamTimeout(Anki::Vector::Void&& new_streamTimeout);
  const Anki::Vector::Void& Get_streamTimeout() const;
  void Set_streamTimeout(const Anki::Vector::Void& new_streamTimeout);
  void Set_streamTimeout(Anki::Vector::Void&& new_streamTimeout);
  
  /** connectionResult **/
  static Message CreateconnectionResult(Anki::Vector::CloudMic::ConnectionResult&& new_connectionResult);
  explicit Message(Anki::Vector::CloudMic::ConnectionResult&& new_connectionResult);
  const Anki::Vector::CloudMic::ConnectionResult& Get_connectionResult() const;
  void Set_connectionResult(const Anki::Vector::CloudMic::ConnectionResult& new_connectionResult);
  void Set_connectionResult(Anki::Vector::CloudMic::ConnectionResult&& new_connectionResult);
  
  /** debugFile **/
  static Message CreatedebugFile(Anki::Vector::CloudMic::Filename&& new_debugFile);
  explicit Message(Anki::Vector::CloudMic::Filename&& new_debugFile);
  const Anki::Vector::CloudMic::Filename& Get_debugFile() const;
  void Set_debugFile(const Anki::Vector::CloudMic::Filename& new_debugFile);
  void Set_debugFile(Anki::Vector::CloudMic::Filename&& new_debugFile);
  
  /** result **/
  static Message Createresult(Anki::Vector::CloudMic::IntentResult&& new_result);
  explicit Message(Anki::Vector::CloudMic::IntentResult&& new_result);
  const Anki::Vector::CloudMic::IntentResult& Get_result() const;
  void Set_result(const Anki::Vector::CloudMic::IntentResult& new_result);
  void Set_result(Anki::Vector::CloudMic::IntentResult&& new_result);
  
  /** error **/
  static Message Createerror(Anki::Vector::CloudMic::IntentError&& new_error);
  explicit Message(Anki::Vector::CloudMic::IntentError&& new_error);
  const Anki::Vector::CloudMic::IntentError& Get_error() const;
  void Set_error(const Anki::Vector::CloudMic::IntentError& new_error);
  void Set_error(Anki::Vector::CloudMic::IntentError&& new_error);
  
  /** streamOpen **/
  static Message CreatestreamOpen(Anki::Vector::CloudMic::StreamOpen&& new_streamOpen);
  explicit Message(Anki::Vector::CloudMic::StreamOpen&& new_streamOpen);
  const Anki::Vector::CloudMic::StreamOpen& Get_streamOpen() const;
  void Set_streamOpen(const Anki::Vector::CloudMic::StreamOpen& new_streamOpen);
  void Set_streamOpen(Anki::Vector::CloudMic::StreamOpen&& new_streamOpen);
  
  size_t Unpack(const uint8_t* buff, const size_t len);
  size_t Unpack(const CLAD::SafeMessageBuffer& buffer);
  
  size_t Pack(uint8_t* buff, size_t len) const;
  size_t Pack(CLAD::SafeMessageBuffer& buffer) const;
  
  size_t Size() const;
  
  bool operator==(const Message& other) const;
  bool operator!=(const Message& other) const;
  /**** JSON ****/
  Json::Value GetJSON() const;
  bool SetFromJSON(const Json::Value& json);
  
private:
  void ClearCurrent();
  Tag _tag;
  
  union {
    Anki::Vector::CloudMic::Hotword _hotword;
    Anki::Vector::CloudMic::AudioData _audio;
    Anki::Vector::Void _audioDone;
    Anki::Vector::Void _connectionCheck;
    Anki::Vector::Void _stopSignal;
    Anki::Vector::Void _testStarted;
    Anki::Vector::Void _streamTimeout;
    Anki::Vector::CloudMic::ConnectionResult _connectionResult;
    Anki::Vector::CloudMic::Filename _debugFile;
    Anki::Vector::CloudMic::IntentResult _result;
    Anki::Vector::CloudMic::IntentError _error;
    Anki::Vector::CloudMic::StreamOpen _streamOpen;
  };
};
extern const char* MessageVersionHashStr;
extern const uint8_t MessageVersionHash[16];

} // namespace CloudMic

} // namespace Vector

} // namespace Anki

#endif // __CLAD_CLOUD_MIC_H__
