// Autogenerated C++ Lite (embedded) message buffer code.
// Source: clad/robotInterface/messageEngineToRobot.clad
// Full command line: victor-clad/tools/message-buffers/emitters/CPPLite_emitter.py --max-message-size 1400 --max-message-size 1400 -C src -I robot/clad/src coretech/vision/clad_src -o generated/clad/robot clad/robotInterface/messageEngineToRobot.clad

#ifndef __CLAD_ROBOT_INTERFACE_MESSAGE_ENGINE_TO_ROBOT_H__
#define __CLAD_ROBOT_INTERFACE_MESSAGE_ENGINE_TO_ROBOT_H__

#include <stdbool.h>
#include <stdint.h>
#include <string>

#include "clad/audio/audioMessage.h"
#include "clad/types/animationTypes.h"
#include "clad/types/backpackAnimationTriggers.h"
#include "clad/types/cameraFOVInfo.h"
#include "clad/types/compositeImageTypes.h"
#include "clad/types/controllerChannels.h"
#include "clad/types/dockingSignals.h"
#include "clad/types/imu.h"
#include "clad/types/lcdTypes.h"
#include "clad/types/ledTypes.h"
#include "clad/types/motorTypes.h"
#include "clad/types/proceduralFaceTypes.h"
#include "clad/types/proxMessages.h"
#include "clad/types/robotStatusAndActions.h"
#include "clad/types/robotTestModes.h"
#include "clad/types/switchboardToRobot.h"
#include "clad/types/textToSpeechTypes.h"
#include "clad/types/tofDisplayTypes.h"
#include "clad/types/sdkAudioTypes.h"

namespace Anki {

namespace Vector {

namespace RobotInterface {

// MESSAGE CheckCloudConnectivity
struct CheckCloudConnectivity
{
  // To conform to C99 standard (6.7.2.1)
  char _empty;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 0;
  static const uint32_t MIN_SIZE = 0;
  inline uint32_t Size() const { return 0; }
  
};

// MESSAGE StartMotorCalibration
struct StartMotorCalibration
{
  bool calibrateHead;
  bool calibrateLift;
  Anki::Vector::MotorCalibrationReason reason;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 3;
  static const uint32_t MIN_SIZE = 3;
  inline uint32_t Size() const { return 3; }
  
};

// MESSAGE DriveWheels
struct DriveWheels
{
  float lwheel_speed_mmps;
  float rwheel_speed_mmps;
  float lwheel_accel_mmps2 = 0.0;
  float rwheel_accel_mmps2 = 0.0;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 16;
  static const uint32_t MIN_SIZE = 16;
  inline uint32_t Size() const { return 16; }
  
};

// MESSAGE DriveWheelsCurvature
struct DriveWheelsCurvature
{
  float speed;
  float accel;
  int16_t curvatureRadius_mm;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 10;
  static const uint32_t MIN_SIZE = 10;
  inline uint32_t Size() const { return 10; }
  
};

// MESSAGE MoveLift
struct MoveLift
{
  float speed_rad_per_sec;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 4;
  static const uint32_t MIN_SIZE = 4;
  inline uint32_t Size() const { return 4; }
  
};

// MESSAGE MoveHead
struct MoveHead
{
  float speed_rad_per_sec;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 4;
  static const uint32_t MIN_SIZE = 4;
  inline uint32_t Size() const { return 4; }
  
};

// MESSAGE SetLiftHeight
struct SetLiftHeight
{
  float height_mm;
  float max_speed_rad_per_sec;
  float accel_rad_per_sec2;
  float duration_sec;
  uint8_t actionID = 0;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 17;
  static const uint32_t MIN_SIZE = 17;
  inline uint32_t Size() const { return 17; }
  
};

// MESSAGE SetLiftAngle
struct SetLiftAngle
{
  float angle_rad;
  float max_speed_rad_per_sec;
  float accel_rad_per_sec2;
  float duration_sec;
  uint8_t actionID = 0;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 17;
  static const uint32_t MIN_SIZE = 17;
  inline uint32_t Size() const { return 17; }
  
};

// MESSAGE SetHeadAngle
struct SetHeadAngle
{
  float angle_rad;
  float max_speed_rad_per_sec;
  float accel_rad_per_sec2;
  float duration_sec;
  uint8_t actionID = 0;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 17;
  static const uint32_t MIN_SIZE = 17;
  inline uint32_t Size() const { return 17; }
  
};

// MESSAGE SetBodyAngle
struct SetBodyAngle
{
  float angle_rad;
  float max_speed_rad_per_sec;
  float accel_rad_per_sec2;
  float angle_tolerance;
  uint16_t num_half_revolutions;
  bool use_shortest_direction;
  uint8_t actionID = 0;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 20;
  static const uint32_t MIN_SIZE = 20;
  inline uint32_t Size() const { return 20; }
  
};

// MESSAGE TurnInPlaceAtSpeed
struct TurnInPlaceAtSpeed
{
  float speed_rad_per_sec;
  float accel_rad_per_sec2;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 8;
  static const uint32_t MIN_SIZE = 8;
  inline uint32_t Size() const { return 8; }
  
};

// MESSAGE StopAllMotors
struct StopAllMotors
{
  // To conform to C99 standard (6.7.2.1)
  char _empty;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 0;
  static const uint32_t MIN_SIZE = 0;
  inline uint32_t Size() const { return 0; }
  
};

// MESSAGE ClearPath
struct ClearPath
{
  uint16_t pathID;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 2;
  static const uint32_t MIN_SIZE = 2;
  inline uint32_t Size() const { return 2; }
  
};

// MESSAGE PathSegmentSpeed
struct PathSegmentSpeed
{
  float target;
  float accel;
  float decel;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 12;
  static const uint32_t MIN_SIZE = 12;
  inline uint32_t Size() const { return 12; }
  
};

// MESSAGE AppendPathSegmentLine
struct AppendPathSegmentLine
{
  float x_start_mm;
  float y_start_mm;
  float x_end_mm;
  float y_end_mm;
  Anki::Vector::RobotInterface::PathSegmentSpeed speed;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 28;
  static const uint32_t MIN_SIZE = 28;
  inline uint32_t Size() const { return 28; }
  
};

// MESSAGE AppendPathSegmentArc
struct AppendPathSegmentArc
{
  float x_center_mm;
  float y_center_mm;
  float radius_mm;
  float startRad;
  float sweepRad;
  Anki::Vector::RobotInterface::PathSegmentSpeed speed;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 32;
  static const uint32_t MIN_SIZE = 32;
  inline uint32_t Size() const { return 32; }
  
};

// MESSAGE AppendPathSegmentPointTurn
struct AppendPathSegmentPointTurn
{
  float x_center_mm;
  float y_center_mm;
  float startRad;
  float targetRad;
  float angleTolerance;
  Anki::Vector::RobotInterface::PathSegmentSpeed speed;
  bool useShortestDir;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 33;
  static const uint32_t MIN_SIZE = 33;
  inline uint32_t Size() const { return 33; }
  
};

// MESSAGE TrimPath
struct TrimPath
{
  uint8_t numPopFrontSegments;
  uint8_t numPopBackSegments;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 2;
  static const uint32_t MIN_SIZE = 2;
  inline uint32_t Size() const { return 2; }
  
};

// MESSAGE ExecutePath
struct ExecutePath
{
  uint16_t pathID;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 2;
  static const uint32_t MIN_SIZE = 2;
  inline uint32_t Size() const { return 2; }
  
};

// MESSAGE AbsoluteLocalizationUpdate
struct AbsoluteLocalizationUpdate
{
  uint32_t timestamp;
  uint32_t pose_frame_id;
  uint32_t origin_id;
  float xPosition;
  float yPosition;
  float headingAngle;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 24;
  static const uint32_t MIN_SIZE = 24;
  inline uint32_t Size() const { return 24; }
  
};

// MESSAGE ForceDelocalizeSimulatedRobot
struct ForceDelocalizeSimulatedRobot
{
  // To conform to C99 standard (6.7.2.1)
  char _empty;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 0;
  static const uint32_t MIN_SIZE = 0;
  inline uint32_t Size() const { return 0; }
  
};

// MESSAGE SyncRobot
struct SyncRobot
{
  // To conform to C99 standard (6.7.2.1)
  char _empty;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 0;
  static const uint32_t MIN_SIZE = 0;
  inline uint32_t Size() const { return 0; }
  
};

// MESSAGE EngineFullyLoaded
struct EngineFullyLoaded
{
  // To conform to C99 standard (6.7.2.1)
  char _empty;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 0;
  static const uint32_t MIN_SIZE = 0;
  inline uint32_t Size() const { return 0; }
  
};

// MESSAGE CalmPowerMode
struct CalmPowerMode
{
  bool enable;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 1;
  static const uint32_t MIN_SIZE = 1;
  inline uint32_t Size() const { return 1; }
  
};

// MESSAGE Shutdown
struct Shutdown
{
  // To conform to C99 standard (6.7.2.1)
  char _empty;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 0;
  static const uint32_t MIN_SIZE = 0;
  inline uint32_t Size() const { return 0; }
  
};

// MESSAGE ControllerGains
struct ControllerGains
{
  float kp;
  float ki;
  float kd;
  float maxIntegralError;
  Anki::Vector::ControllerChannel controller;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 17;
  static const uint32_t MIN_SIZE = 17;
  inline uint32_t Size() const { return 17; }
  
};

// MESSAGE RollActionParams
struct RollActionParams
{
  float liftHeight_mm;
  float driveSpeed_mmps;
  float driveAccel_mmps2;
  uint32_t driveDuration_ms;
  float backupDist_mm;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 20;
  static const uint32_t MIN_SIZE = 20;
  inline uint32_t Size() const { return 20; }
  
};

// MESSAGE PlaypenStart
struct PlaypenStart
{
  // To conform to C99 standard (6.7.2.1)
  char _empty;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 0;
  static const uint32_t MIN_SIZE = 0;
  inline uint32_t Size() const { return 0; }
  
};

// MESSAGE SelfTestEnd
struct SelfTestEnd
{
  // To conform to C99 standard (6.7.2.1)
  char _empty;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 0;
  static const uint32_t MIN_SIZE = 0;
  inline uint32_t Size() const { return 0; }
  
};

// MESSAGE PrintBodyData
struct PrintBodyData
{
  uint32_t period_tics;
  bool motors;
  bool prox;
  bool battery;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 7;
  static const uint32_t MIN_SIZE = 7;
  inline uint32_t Size() const { return 7; }
  
};

// MESSAGE SetMotionModelParams
struct SetMotionModelParams
{
  float slipFactor;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 4;
  static const uint32_t MIN_SIZE = 4;
  inline uint32_t Size() const { return 4; }
  
};

// MESSAGE BackpackSetLayer
struct BackpackSetLayer
{
  uint8_t layer;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 1;
  static const uint32_t MIN_SIZE = 1;
  inline uint32_t Size() const { return 1; }
  
};

// MESSAGE CheckLiftLoad
struct CheckLiftLoad
{
  // To conform to C99 standard (6.7.2.1)
  char _empty;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 0;
  static const uint32_t MIN_SIZE = 0;
  inline uint32_t Size() const { return 0; }
  
};

// MESSAGE EnableMotorPower
struct EnableMotorPower
{
  Anki::Vector::MotorID motorID;
  bool enable;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 2;
  static const uint32_t MIN_SIZE = 2;
  inline uint32_t Size() const { return 2; }
  
};

// MESSAGE RobotStoppedAck
struct RobotStoppedAck
{
  // To conform to C99 standard (6.7.2.1)
  char _empty;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 0;
  static const uint32_t MIN_SIZE = 0;
  inline uint32_t Size() const { return 0; }
  
};

// MESSAGE EnableStopOnCliff
struct EnableStopOnCliff
{
  bool enable;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 1;
  static const uint32_t MIN_SIZE = 1;
  inline uint32_t Size() const { return 1; }
  
};

// MESSAGE EnableStopOnWhite
struct EnableStopOnWhite
{
  bool enable;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 1;
  static const uint32_t MIN_SIZE = 1;
  inline uint32_t Size() const { return 1; }
  
};

// MESSAGE CliffAlignToWhiteAction
struct CliffAlignToWhiteAction
{
  bool start;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 1;
  static const uint32_t MIN_SIZE = 1;
  inline uint32_t Size() const { return 1; }
  
};

// MESSAGE EnableBraceWhenFalling
struct EnableBraceWhenFalling
{
  bool enable;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 1;
  static const uint32_t MIN_SIZE = 1;
  inline uint32_t Size() const { return 1; }
  
};

// MESSAGE PlayAnim
struct PlayAnim
{
  uint32_t numLoops = 1;
  uint32_t startAt_ms = 0;
  uint8_t tag;
  bool renderInEyeHue = 1;
  uint8_t animName_length;
  char animName[255];
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const;
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 266;
  static const uint32_t MIN_SIZE = 11;
  uint32_t Size() const;
  
};

// MESSAGE AbortAnimation
struct AbortAnimation
{
  uint8_t tag;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 1;
  static const uint32_t MIN_SIZE = 1;
  inline uint32_t Size() const { return 1; }
  
};

// MESSAGE EnableKeepFaceAlive
struct EnableKeepFaceAlive
{
  uint32_t disableTimeout_ms;
  bool enable;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 5;
  static const uint32_t MIN_SIZE = 5;
  inline uint32_t Size() const { return 5; }
  
};

// MESSAGE SetKeepFaceAliveFocus
struct SetKeepFaceAliveFocus
{
  bool enable;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 1;
  static const uint32_t MIN_SIZE = 1;
  inline uint32_t Size() const { return 1; }
  
};

// MESSAGE AddOrUpdateEyeShift
struct AddOrUpdateEyeShift
{
  float xPix;
  float yPix;
  uint32_t duration_ms;
  float xMax;
  float yMax;
  float lookUpMaxScale;
  float lookDownMinScale;
  float outerEyeScaleIncrease;
  uint8_t name_length;
  char name[255];
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const;
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 288;
  static const uint32_t MIN_SIZE = 33;
  uint32_t Size() const;
  
};

// MESSAGE RemoveEyeShift
struct RemoveEyeShift
{
  uint32_t disableTimeout_ms;
  uint8_t name_length;
  char name[255];
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const;
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 260;
  static const uint32_t MIN_SIZE = 5;
  uint32_t Size() const;
  
};

// MESSAGE AddSquint
struct AddSquint
{
  float squintScaleX;
  float squintScaleY;
  float upperLidAngle;
  uint8_t name_length;
  char name[255];
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const;
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 268;
  static const uint32_t MIN_SIZE = 13;
  uint32_t Size() const;
  
};

// MESSAGE RemoveSquint
struct RemoveSquint
{
  uint32_t disableTimeout_ms;
  uint8_t name_length;
  char name[255];
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const;
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 260;
  static const uint32_t MIN_SIZE = 5;
  uint32_t Size() const;
  
};

// MESSAGE SetFullAnimTrackLockState
struct SetFullAnimTrackLockState
{
  uint8_t trackLockState;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 1;
  static const uint32_t MIN_SIZE = 1;
  inline uint32_t Size() const { return 1; }
  
};

// MESSAGE AddAnim
struct AddAnim
{
  uint8_t animPath_length;
  char animPath[255];
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const;
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 256;
  static const uint32_t MIN_SIZE = 1;
  uint32_t Size() const;
  
};

// MESSAGE RecordHeading
struct RecordHeading
{
  // To conform to C99 standard (6.7.2.1)
  char _empty;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 0;
  static const uint32_t MIN_SIZE = 0;
  inline uint32_t Size() const { return 0; }
  
};

// MESSAGE TurnToRecordedHeading
struct TurnToRecordedHeading
{
  int16_t offset_deg;
  int16_t speed_degPerSec;
  int16_t accel_degPerSec2;
  int16_t decel_degPerSec2;
  uint16_t tolerance_deg;
  uint16_t numHalfRevs;
  bool useShortestDir;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 13;
  static const uint32_t MIN_SIZE = 13;
  inline uint32_t Size() const { return 13; }
  
};

// MESSAGE SetBackpackLights
struct SetBackpackLights
{
  Anki::Vector::LightState lights[3];
  uint8_t layer = 0;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 61;
  static const uint32_t MIN_SIZE = 61;
  inline uint32_t Size() const { return 61; }
  
};

// MESSAGE SetSystemLight
struct SetSystemLight
{
  Anki::Vector::LightState light;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 20;
  static const uint32_t MIN_SIZE = 20;
  inline uint32_t Size() const { return 20; }
  
};

// MESSAGE StartRecordingMicsRaw
struct StartRecordingMicsRaw
{
  uint32_t duration_ms;
  bool runFFT;
  uint8_t path_length;
  char path[255];
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const;
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 261;
  static const uint32_t MIN_SIZE = 6;
  uint32_t Size() const;
  
};

// MESSAGE StartRecordingMicsProcessed
struct StartRecordingMicsProcessed
{
  uint32_t duration_ms;
  uint8_t path_length;
  char path[255];
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const;
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 260;
  static const uint32_t MIN_SIZE = 5;
  uint32_t Size() const;
  
};

// MESSAGE StartPlaybackAudio
struct StartPlaybackAudio
{
  uint8_t path_length;
  char path[255];
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const;
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 256;
  static const uint32_t MIN_SIZE = 1;
  uint32_t Size() const;
  
};

// MESSAGE StartWakeWordlessStreaming
struct StartWakeWordlessStreaming
{
  uint8_t streamType;
  bool playGetInFromAnimProcess;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 2;
  static const uint32_t MIN_SIZE = 2;
  inline uint32_t Size() const { return 2; }
  
};

// MESSAGE SetTriggerWordResponse
struct SetTriggerWordResponse
{
  Anki::AudioEngine::Multiplexer::PostAudioEvent postAudioEvent;
  int32_t minStreamingDuration_ms = -1;
  bool shouldTriggerWordStartStream = 0;
  bool shouldTriggerWordSimulateStream = 0;
  uint8_t getInAnimationTag = 0;
  uint8_t getInAnimationName_length;
  char getInAnimationName[255];
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const;
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 279;
  static const uint32_t MIN_SIZE = 24;
  uint32_t Size() const;
  
};

// MESSAGE SetAlexaUXResponses
struct SetAlexaUXResponses
{
  Anki::AudioEngine::Multiplexer::PostAudioEvent postAudioEvents[4];
  uint8_t getInAnimTags[4];
  uint8_t csvGetInAnimNames_length;
  char csvGetInAnimNames[255];
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const;
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 324;
  static const uint32_t MIN_SIZE = 69;
  uint32_t Size() const;
  
};

// MESSAGE ResetBeatDetector
struct ResetBeatDetector
{
  // To conform to C99 standard (6.7.2.1)
  char _empty;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 0;
  static const uint32_t MIN_SIZE = 0;
  inline uint32_t Size() const { return 0; }
  
};

// MESSAGE SetAlexaUsage
struct SetAlexaUsage
{
  bool optedIn;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 1;
  static const uint32_t MIN_SIZE = 1;
  inline uint32_t Size() const { return 1; }
  
};

// STRUCTURE ColorRGB
struct ColorRGB
{
  uint8_t r;
  uint8_t g;
  uint8_t b;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 3;
  static const uint32_t MIN_SIZE = 3;
  inline uint32_t Size() const { return 3; }
  
};

// MESSAGE DrawTextOnScreen
struct DrawTextOnScreen
{
  bool drawNow = 0;
  Anki::Vector::RobotInterface::ColorRGB textColor;
  Anki::Vector::RobotInterface::ColorRGB bgColor;
  uint8_t text_length;
  char text[255];
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const;
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 263;
  static const uint32_t MIN_SIZE = 8;
  uint32_t Size() const;
  
};

// MESSAGE ShowUrlFace
struct ShowUrlFace
{
  bool show;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 1;
  static const uint32_t MIN_SIZE = 1;
  inline uint32_t Size() const { return 1; }
  
};

// MESSAGE ExitCCScreen
struct ExitCCScreen
{
  // To conform to C99 standard (6.7.2.1)
  char _empty;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 0;
  static const uint32_t MIN_SIZE = 0;
  inline uint32_t Size() const { return 0; }
  
};

// MESSAGE EnableMirrorModeScreen
struct EnableMirrorModeScreen
{
  bool enable;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 1;
  static const uint32_t MIN_SIZE = 1;
  inline uint32_t Size() const { return 1; }
  
};

// MESSAGE DisplayProceduralFace
struct DisplayProceduralFace
{
  Anki::Vector::ProceduralFaceParameters faceParams;
  uint32_t duration_ms;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 228;
  static const uint32_t MIN_SIZE = 228;
  inline uint32_t Size() const { return 228; }
  
};

// MESSAGE SetFaceHue
struct SetFaceHue
{
  float hue;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 4;
  static const uint32_t MIN_SIZE = 4;
  inline uint32_t Size() const { return 4; }
  
};

// MESSAGE SetFaceSaturation
struct SetFaceSaturation
{
  float saturation;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 4;
  static const uint32_t MIN_SIZE = 4;
  inline uint32_t Size() const { return 4; }
  
};

// MESSAGE SetButtonWakeWord
struct SetButtonWakeWord
{
  bool isAlexa;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 1;
  static const uint32_t MIN_SIZE = 1;
  inline uint32_t Size() const { return 1; }
  
};

// STRUCTURE SpriteBoxRemap
struct SpriteBoxRemap
{
  Anki::Vision::SpriteBoxName spriteBoxName;
  uint8_t padding;
  uint16_t remappedAssetID;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 4;
  static const uint32_t MIN_SIZE = 4;
  inline uint32_t Size() const { return 4; }
  
};

// MESSAGE PlayAnimWithSpriteBoxRemaps
struct PlayAnimWithSpriteBoxRemaps
{
  uint8_t tag;
  uint8_t numRemaps;
  Anki::Vector::RobotInterface::SpriteBoxRemap spriteBoxRemaps[150];
  bool lockFaceAtEndOfAnim;
  uint8_t animName_length;
  char animName[255];
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const;
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 859;
  static const uint32_t MIN_SIZE = 604;
  uint32_t Size() const;
  
};

// MESSAGE PlayAnimWithSpriteBoxKeyFrames
struct PlayAnimWithSpriteBoxKeyFrames
{
  Anki::Vision::SpriteBoxKeyFrame spriteBoxKeyFrames[40];
  uint8_t tag;
  uint8_t numKeyFrames;
  uint8_t animName_length;
  char animName[255];
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const;
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 1218;
  static const uint32_t MIN_SIZE = 963;
  uint32_t Size() const;
  
};

// MESSAGE AddSpriteBoxKeyFrames
struct AddSpriteBoxKeyFrames
{
  Anki::Vision::SpriteBoxKeyFrame spriteBoxKeyFrames[50];
  uint8_t numKeyFrames;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 1201;
  static const uint32_t MIN_SIZE = 1201;
  inline uint32_t Size() const { return 1201; }
  
};

// MESSAGE DisplayFaceImageBinaryChunk
struct DisplayFaceImageBinaryChunk
{
  uint32_t duration_ms;
  uint8_t faceData[1104];
  uint8_t imageId;
  uint8_t chunkIndex;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 1110;
  static const uint32_t MIN_SIZE = 1110;
  inline uint32_t Size() const { return 1110; }
  
};

// MESSAGE DisplayFaceImageGrayscaleChunk
struct DisplayFaceImageGrayscaleChunk
{
  uint32_t duration_ms;
  uint8_t faceData[1200];
  uint16_t numPixels;
  uint8_t imageId;
  uint8_t chunkIndex;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 1208;
  static const uint32_t MIN_SIZE = 1208;
  inline uint32_t Size() const { return 1208; }
  
};

// MESSAGE DisplayFaceImageRGBChunk
struct DisplayFaceImageRGBChunk
{
  uint32_t duration_ms;
  uint16_t faceData[600];
  uint16_t numPixels;
  uint8_t imageId;
  uint8_t chunkIndex;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 1208;
  static const uint32_t MIN_SIZE = 1208;
  inline uint32_t Size() const { return 1208; }
  
};

// MESSAGE FakeWakeWordFromExternalInterface
struct FakeWakeWordFromExternalInterface
{
  // To conform to C99 standard (6.7.2.1)
  char _empty;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 0;
  static const uint32_t MIN_SIZE = 0;
  inline uint32_t Size() const { return 0; }
  
};

// MESSAGE SetDebugConsoleVarMessage
struct SetDebugConsoleVarMessage
{
  uint8_t varName[64];
  uint8_t tryValue[16];
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 80;
  static const uint32_t MIN_SIZE = 80;
  inline uint32_t Size() const { return 80; }
  
};

// MESSAGE RunDebugConsoleFuncMessage
struct RunDebugConsoleFuncMessage
{
  uint8_t funcName[64];
  uint8_t funcArgs[64];
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 128;
  static const uint32_t MIN_SIZE = 128;
  inline uint32_t Size() const { return 128; }
  
};

// MESSAGE TextToSpeechPrepare
struct TextToSpeechPrepare
{
  Anki::AudioMetaData::SwitchState::Robot_Vic_External_Processing style;
  float durationScalar;
  float pitchScalar;
  Anki::Vector::TextToSpeechTriggerMode triggerMode;
  uint8_t ttsID;
  int8_t text[1024];
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 1038;
  static const uint32_t MIN_SIZE = 1038;
  inline uint32_t Size() const { return 1038; }
  
};

// MESSAGE TextToSpeechPlay
struct TextToSpeechPlay
{
  uint8_t ttsID;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 1;
  static const uint32_t MIN_SIZE = 1;
  inline uint32_t Size() const { return 1; }
  
};

// MESSAGE TextToSpeechCancel
struct TextToSpeechCancel
{
  uint8_t ttsID;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 1;
  static const uint32_t MIN_SIZE = 1;
  inline uint32_t Size() const { return 1; }
  
};

// MESSAGE AlterStreamingAnimationAtTime
struct AlterStreamingAnimationAtTime
{
  uint32_t relativeStreamTime_ms;
  bool applyBeforeTick = 1;
  uint8_t internalTag;
  Anki::Vector::RobotInterface::SetFullAnimTrackLockState setFullAnimTrackLockState;
  uint8_t padding[1];
  Anki::AudioEngine::Multiplexer::PostAudioEvent postAudioEvent;
  Anki::Vector::RobotInterface::TextToSpeechPlay textToSpeechPlay;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 25;
  static const uint32_t MIN_SIZE = 25;
  inline uint32_t Size() const { return 25; }
  
};

// MESSAGE SetLocale
struct SetLocale
{
  uint8_t locale_length;
  char locale[255];
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const;
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 256;
  static const uint32_t MIN_SIZE = 1;
  uint32_t Size() const;
  
};

// MESSAGE SetLCDBrightnessLevel
struct SetLCDBrightnessLevel
{
  Anki::Vector::LCDBrightness level;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 1;
  static const uint32_t MIN_SIZE = 1;
  inline uint32_t Size() const { return 1; }
  
};

// MESSAGE BatteryStatus
struct BatteryStatus
{
  bool isLow;
  bool isCharging;
  bool onChargerContacts;
  bool isBatteryFull;
  bool isBatteryDisconnected;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 5;
  static const uint32_t MIN_SIZE = 5;
  inline uint32_t Size() const { return 5; }
  
};

// MESSAGE TriggerBackpackAnimation
struct TriggerBackpackAnimation
{
  Anki::Vector::BackpackAnimationTrigger trigger;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 4;
  static const uint32_t MIN_SIZE = 4;
  inline uint32_t Size() const { return 4; }
  
};

// MESSAGE AcousticTestEnabled
struct AcousticTestEnabled
{
  bool enabled;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 1;
  static const uint32_t MIN_SIZE = 1;
  inline uint32_t Size() const { return 1; }
  
};

// MESSAGE ExternalAudioPrepare
struct ExternalAudioPrepare
{
  uint16_t audio_volume;
  uint16_t audio_rate;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 4;
  static const uint32_t MIN_SIZE = 4;
  inline uint32_t Size() const { return 4; }
  
};

// MESSAGE ExternalAudioChunk
struct ExternalAudioChunk
{
  uint16_t audio_chunk_size;
  uint16_t audio_chunk_data[512];
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 1026;
  static const uint32_t MIN_SIZE = 1026;
  inline uint32_t Size() const { return 1026; }
  
};

// MESSAGE ExternalAudioComplete
struct ExternalAudioComplete
{
  // To conform to C99 standard (6.7.2.1)
  char _empty;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 0;
  static const uint32_t MIN_SIZE = 0;
  inline uint32_t Size() const { return 0; }
  
};

// MESSAGE ExternalAudioCancel
struct ExternalAudioCancel
{
  // To conform to C99 standard (6.7.2.1)
  char _empty;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 0;
  static const uint32_t MIN_SIZE = 0;
  inline uint32_t Size() const { return 0; }
  
};

// ENUM SettingBeingChanged
enum class SettingBeingChanged : uint8_t {
  SETTING_ENABLE_DATA_COLLECTION = 0,
  SETTING_TIME_ZONE              = 1,
};

constexpr uint8_t EnumToUnderlyingType(SettingBeingChanged e)
{
  return static_cast<uint8_t>(e);
}

const char* EnumToString(SettingBeingChanged m);
SettingBeingChanged SettingBeingChangedFromString(const std::string&);

// MESSAGE UpdatedSettings
struct UpdatedSettings
{
  Anki::Vector::RobotInterface::SettingBeingChanged settingBeingChanged;
  bool enableDataCollection;
  uint8_t timeZone_length;
  char timeZone[255];
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const;
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 258;
  static const uint32_t MIN_SIZE = 3;
  uint32_t Size() const;
  
};

// MESSAGE RangeDataToDisplay
struct RangeDataToDisplay
{
  Anki::Vector::RangeDataDisplay data;
  
  /**** Cast to/from buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(this); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(this); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const { return true; }
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 256;
  static const uint32_t MIN_SIZE = 256;
  inline uint32_t Size() const { return 256; }
  
};

// ENUM ToRobotAddressSpace
enum class ToRobotAddressSpace : uint32_t {
  GLOBAL_INVALID_TAG  = 0,   
  TO_SUPERVISOR_START = 0x1, 
  TO_SUPERVISOR_END   = 0x4f,
  TO_ANIM_START       = 0x50,
  TO_ANIM_END         = 0xaf,
  TO_ENG_START        = 0xb0,
  TO_ENG_UNREL        = 0xf0,
  TO_ENG_END          = 0xfe,
};

constexpr uint32_t EnumToUnderlyingType(ToRobotAddressSpace e)
{
  return static_cast<uint32_t>(e);
}

const char* EnumToString(ToRobotAddressSpace m);
ToRobotAddressSpace ToRobotAddressSpaceFromString(const std::string&);

// UNION EngineToRobot
struct EngineToRobot
{
  enum {
    Tag_syncRobot                         = 0x2,  // 2
    Tag_shutdown                          = 0x3,  // 3
    Tag_calmPowerMode                     = 0x4,  // 4
    Tag_startControllerTestMode           = 0xa,  // 10
    Tag_setControllerGains                = 0xb,  // 11
    Tag_setMotionModelParams              = 0xc,  // 12
    Tag_rollActionParams                  = 0xd,  // 13
    Tag_playpenStart                      = 0xe,  // 14
    Tag_printBodyData                     = 0xf,  // 15
    Tag_drive                             = 0x10, // 16
    Tag_driveCurvature                    = 0x11, // 17
    Tag_moveLift                          = 0x12, // 18
    Tag_moveHead                          = 0x13, // 19
    Tag_liftHeight                        = 0x14, // 20
    Tag_headAngle                         = 0x15, // 21
    Tag_setLiftAngle                      = 0x16, // 22
    Tag_setBodyAngle                      = 0x17, // 23
    Tag_turnInPlaceAtSpeed                = 0x18, // 24
    Tag_recordHeading                     = 0x19, // 25
    Tag_turnToRecordedHeading             = 0x1a, // 26
    Tag_enableMotorPower                  = 0x1b, // 27
    Tag_stop                              = 0x1c, // 28
    Tag_setBackpackLayer                  = 0x1d, // 29
    Tag_setBackpackLights                 = 0x1e, // 30
    Tag_setSystemLight                    = 0x1f, // 31
    Tag_clearPath                         = 0x20, // 32
    Tag_appendPathSegLine                 = 0x21, // 33
    Tag_appendPathSegArc                  = 0x22, // 34
    Tag_appendPathSegPointTurn            = 0x23, // 35
    Tag_trimPath                          = 0x24, // 36
    Tag_executePath                       = 0x25, // 37
    Tag_dockWithObject                    = 0x26, // 38
    Tag_abortDocking                      = 0x27, // 39
    Tag_placeObjectOnGround               = 0x28, // 40
    Tag_dockingErrorSignal                = 0x2a, // 42
    Tag_setCarryState                     = 0x2b, // 43
    Tag_cameraFOVInfo                     = 0x2c, // 44
    Tag_absLocalizationUpdate             = 0x2d, // 45
    Tag_forceDelocalizeSimulatedRobot     = 0x2e, // 46
    Tag_imuRequest                        = 0x30, // 48
    Tag_checkLiftLoad                     = 0x31, // 49
    Tag_setCliffDetectThresholds          = 0x32, // 50
    Tag_setWhiteDetectThresholds          = 0x39, // 57
    Tag_startMotorCalibration             = 0x33, // 51
    Tag_enableStopOnCliff                 = 0x34, // 52
    Tag_enableBraceWhenFalling            = 0x35, // 53
    Tag_robotStoppedAck                   = 0x36, // 54
    Tag_cliffAlignToWhiteAction           = 0x37, // 55
    Tag_enableStopOnWhite                 = 0x38, // 56
    Tag_playAnim                          = 0x50, // 80
    Tag_setFullAnimTrackLockState         = 0x51, // 81
    Tag_addAnim                           = 0x52, // 82
    Tag_abortAnimation                    = 0x53, // 83
    Tag_setLocale                         = 0x54, // 84
    Tag_drawTextOnScreen                  = 0x55, // 85
    Tag_displayProceduralFace             = 0x56, // 86
    Tag_setFaceHue                        = 0x57, // 87
    Tag_setFaceSaturation                 = 0x58, // 88
    Tag_displayFaceImageBinaryChunk       = 0x59, // 89
    Tag_displayFaceImageRGBChunk          = 0x5a, // 90
    Tag_setKeepFaceAliveFocus             = 0x5c, // 92
    Tag_enableKeepFaceAlive               = 0x5d, // 93
    Tag_addOrUpdateEyeShift               = 0x5e, // 94
    Tag_removeEyeShift                    = 0x5f, // 95
    Tag_addSquint                         = 0x60, // 96
    Tag_removeSquint                      = 0x61, // 97
    Tag_displayFaceImageGrayscaleChunk    = 0x62, // 98
    Tag_playAnimWithSpriteBoxRemaps       = 0x63, // 99
    Tag_playAnimWithSpriteBoxKeyFrames    = 0x64, // 100
    Tag_addSpriteBoxKeyFrames             = 0x65, // 101
    Tag_enableMirrorModeScreen            = 0x66, // 102
    Tag_setButtonWakeWord                 = 0x67, // 103
    Tag_postAudioEvent                    = 0x70, // 112
    Tag_stopAllAudioEvents                = 0x71, // 113
    Tag_postAudioGameState                = 0x72, // 114
    Tag_postAudioSwitchState              = 0x73, // 115
    Tag_postAudioParameter                = 0x74, // 116
    Tag_externalAudioPrepare              = 0x75, // 117
    Tag_externalAudioChunk                = 0x76, // 118
    Tag_externalAudioComplete             = 0x77, // 119
    Tag_externalAudioCancel               = 0x78, // 120
    Tag_fakeWakeWordFromExternalInterface = 0x80, // 128
    Tag_showUrlFace                       = 0x81, // 129
    Tag_exitCCScreen                      = 0x82, // 130
    Tag_setDebugConsoleVarMessage         = 0x90, // 144
    Tag_runDebugConsoleFuncMessage        = 0x91, // 145
    Tag_textToSpeechPrepare               = 0x92, // 146
    Tag_textToSpeechPlay                  = 0x94, // 148
    Tag_textToSpeechCancel                = 0x95, // 149
    Tag_startRecordingMicsRaw             = 0x96, // 150
    Tag_startRecordingMicsProcessed       = 0x97, // 151
    Tag_playbackAudioStart                = 0x98, // 152
    Tag_startWakeWordlessStreaming        = 0x99, // 153
    Tag_setTriggerWordResponse            = 0x9a, // 154
    Tag_setAlexaUXResponses               = 0x9b, // 155
    Tag_resetBeatDetector                 = 0x9c, // 156
    Tag_setAlexaUsage                     = 0x9d, // 157
    Tag_setConnectionStatus               = 0xa0, // 160
    Tag_setBLEPin                         = 0xa1, // 161
    Tag_alterStreamingAnimation           = 0xa2, // 162
    Tag_sendBLEConnectionStatus           = 0xa3, // 163
    Tag_selfTestEnd                       = 0xa4, // 164
    Tag_acousticTestEnabled               = 0xa5, // 165
    Tag_rangeDataToDisplay                = 0xa6, // 166
    Tag_setLCDBrightnessLevel             = 0xaa, // 170
    Tag_batteryStatus                     = 0xab, // 171
    Tag_triggerBackpackAnimation          = 0xac, // 172
    Tag_engineFullyLoaded                 = 0xad, // 173
    Tag_checkCloudConnectivity            = 0xae, // 174
    Tag_updatedSettings                   = 0xaf, // 175
    INVALID                               = 255
  };
  typedef uint8_t Tag;
  
  /**** Padding added to preserve alignment ****/
  char _padding[7];
  
  Tag tag;
  
  union {
    Anki::Vector::RobotInterface::SyncRobot syncRobot;
    Anki::Vector::RobotInterface::Shutdown shutdown;
    Anki::Vector::RobotInterface::CalmPowerMode calmPowerMode;
    Anki::Vector::StartControllerTestMode startControllerTestMode;
    Anki::Vector::RobotInterface::ControllerGains setControllerGains;
    Anki::Vector::RobotInterface::SetMotionModelParams setMotionModelParams;
    Anki::Vector::RobotInterface::RollActionParams rollActionParams;
    Anki::Vector::RobotInterface::PlaypenStart playpenStart;
    Anki::Vector::RobotInterface::PrintBodyData printBodyData;
    Anki::Vector::RobotInterface::DriveWheels drive;
    Anki::Vector::RobotInterface::DriveWheelsCurvature driveCurvature;
    Anki::Vector::RobotInterface::MoveLift moveLift;
    Anki::Vector::RobotInterface::MoveHead moveHead;
    Anki::Vector::RobotInterface::SetLiftHeight liftHeight;
    Anki::Vector::RobotInterface::SetHeadAngle headAngle;
    Anki::Vector::RobotInterface::SetLiftAngle setLiftAngle;
    Anki::Vector::RobotInterface::SetBodyAngle setBodyAngle;
    Anki::Vector::RobotInterface::TurnInPlaceAtSpeed turnInPlaceAtSpeed;
    Anki::Vector::RobotInterface::RecordHeading recordHeading;
    Anki::Vector::RobotInterface::TurnToRecordedHeading turnToRecordedHeading;
    Anki::Vector::RobotInterface::EnableMotorPower enableMotorPower;
    Anki::Vector::RobotInterface::StopAllMotors stop;
    Anki::Vector::RobotInterface::BackpackSetLayer setBackpackLayer;
    Anki::Vector::RobotInterface::SetBackpackLights setBackpackLights;
    Anki::Vector::RobotInterface::SetSystemLight setSystemLight;
    Anki::Vector::RobotInterface::ClearPath clearPath;
    Anki::Vector::RobotInterface::AppendPathSegmentLine appendPathSegLine;
    Anki::Vector::RobotInterface::AppendPathSegmentArc appendPathSegArc;
    Anki::Vector::RobotInterface::AppendPathSegmentPointTurn appendPathSegPointTurn;
    Anki::Vector::RobotInterface::TrimPath trimPath;
    Anki::Vector::RobotInterface::ExecutePath executePath;
    Anki::Vector::DockWithObject dockWithObject;
    Anki::Vector::AbortDocking abortDocking;
    Anki::Vector::PlaceObjectOnGround placeObjectOnGround;
    Anki::Vector::DockingErrorSignal dockingErrorSignal;
    Anki::Vector::CarryStateUpdate setCarryState;
    Anki::Vector::CameraFOVInfo cameraFOVInfo;
    Anki::Vector::RobotInterface::AbsoluteLocalizationUpdate absLocalizationUpdate;
    Anki::Vector::RobotInterface::ForceDelocalizeSimulatedRobot forceDelocalizeSimulatedRobot;
    Anki::Vector::IMURequest imuRequest;
    Anki::Vector::RobotInterface::CheckLiftLoad checkLiftLoad;
    Anki::Vector::SetCliffDetectThresholds setCliffDetectThresholds;
    Anki::Vector::SetWhiteDetectThresholds setWhiteDetectThresholds;
    Anki::Vector::RobotInterface::StartMotorCalibration startMotorCalibration;
    Anki::Vector::RobotInterface::EnableStopOnCliff enableStopOnCliff;
    Anki::Vector::RobotInterface::EnableBraceWhenFalling enableBraceWhenFalling;
    Anki::Vector::RobotInterface::RobotStoppedAck robotStoppedAck;
    Anki::Vector::RobotInterface::CliffAlignToWhiteAction cliffAlignToWhiteAction;
    Anki::Vector::RobotInterface::EnableStopOnWhite enableStopOnWhite;
    Anki::Vector::RobotInterface::PlayAnim playAnim;
    Anki::Vector::RobotInterface::SetFullAnimTrackLockState setFullAnimTrackLockState;
    Anki::Vector::RobotInterface::AddAnim addAnim;
    Anki::Vector::RobotInterface::AbortAnimation abortAnimation;
    Anki::Vector::RobotInterface::SetLocale setLocale;
    Anki::Vector::RobotInterface::DrawTextOnScreen drawTextOnScreen;
    Anki::Vector::RobotInterface::DisplayProceduralFace displayProceduralFace;
    Anki::Vector::RobotInterface::SetFaceHue setFaceHue;
    Anki::Vector::RobotInterface::SetFaceSaturation setFaceSaturation;
    Anki::Vector::RobotInterface::DisplayFaceImageBinaryChunk displayFaceImageBinaryChunk;
    Anki::Vector::RobotInterface::DisplayFaceImageRGBChunk displayFaceImageRGBChunk;
    Anki::Vector::RobotInterface::SetKeepFaceAliveFocus setKeepFaceAliveFocus;
    Anki::Vector::RobotInterface::EnableKeepFaceAlive enableKeepFaceAlive;
    Anki::Vector::RobotInterface::AddOrUpdateEyeShift addOrUpdateEyeShift;
    Anki::Vector::RobotInterface::RemoveEyeShift removeEyeShift;
    Anki::Vector::RobotInterface::AddSquint addSquint;
    Anki::Vector::RobotInterface::RemoveSquint removeSquint;
    Anki::Vector::RobotInterface::DisplayFaceImageGrayscaleChunk displayFaceImageGrayscaleChunk;
    Anki::Vector::RobotInterface::PlayAnimWithSpriteBoxRemaps playAnimWithSpriteBoxRemaps;
    Anki::Vector::RobotInterface::PlayAnimWithSpriteBoxKeyFrames playAnimWithSpriteBoxKeyFrames;
    Anki::Vector::RobotInterface::AddSpriteBoxKeyFrames addSpriteBoxKeyFrames;
    Anki::Vector::RobotInterface::EnableMirrorModeScreen enableMirrorModeScreen;
    Anki::Vector::RobotInterface::SetButtonWakeWord setButtonWakeWord;
    Anki::AudioEngine::Multiplexer::PostAudioEvent postAudioEvent;
    Anki::AudioEngine::Multiplexer::StopAllAudioEvents stopAllAudioEvents;
    Anki::AudioEngine::Multiplexer::PostAudioGameState postAudioGameState;
    Anki::AudioEngine::Multiplexer::PostAudioSwitchState postAudioSwitchState;
    Anki::AudioEngine::Multiplexer::PostAudioParameter postAudioParameter;
    Anki::Vector::RobotInterface::ExternalAudioPrepare externalAudioPrepare;
    Anki::Vector::RobotInterface::ExternalAudioChunk externalAudioChunk;
    Anki::Vector::RobotInterface::ExternalAudioComplete externalAudioComplete;
    Anki::Vector::RobotInterface::ExternalAudioCancel externalAudioCancel;
    Anki::Vector::RobotInterface::FakeWakeWordFromExternalInterface fakeWakeWordFromExternalInterface;
    Anki::Vector::RobotInterface::ShowUrlFace showUrlFace;
    Anki::Vector::RobotInterface::ExitCCScreen exitCCScreen;
    Anki::Vector::RobotInterface::SetDebugConsoleVarMessage setDebugConsoleVarMessage;
    Anki::Vector::RobotInterface::RunDebugConsoleFuncMessage runDebugConsoleFuncMessage;
    Anki::Vector::RobotInterface::TextToSpeechPrepare textToSpeechPrepare;
    Anki::Vector::RobotInterface::TextToSpeechPlay textToSpeechPlay;
    Anki::Vector::RobotInterface::TextToSpeechCancel textToSpeechCancel;
    Anki::Vector::RobotInterface::StartRecordingMicsRaw startRecordingMicsRaw;
    Anki::Vector::RobotInterface::StartRecordingMicsProcessed startRecordingMicsProcessed;
    Anki::Vector::RobotInterface::StartPlaybackAudio playbackAudioStart;
    Anki::Vector::RobotInterface::StartWakeWordlessStreaming startWakeWordlessStreaming;
    Anki::Vector::RobotInterface::SetTriggerWordResponse setTriggerWordResponse;
    Anki::Vector::RobotInterface::SetAlexaUXResponses setAlexaUXResponses;
    Anki::Vector::RobotInterface::ResetBeatDetector resetBeatDetector;
    Anki::Vector::RobotInterface::SetAlexaUsage setAlexaUsage;
    Anki::Vector::SwitchboardInterface::SetConnectionStatus setConnectionStatus;
    Anki::Vector::SwitchboardInterface::SetBLEPin setBLEPin;
    Anki::Vector::RobotInterface::AlterStreamingAnimationAtTime alterStreamingAnimation;
    Anki::Vector::SwitchboardInterface::SendBLEConnectionStatus sendBLEConnectionStatus;
    Anki::Vector::RobotInterface::SelfTestEnd selfTestEnd;
    Anki::Vector::RobotInterface::AcousticTestEnabled acousticTestEnabled;
    Anki::Vector::RobotInterface::RangeDataToDisplay rangeDataToDisplay;
    Anki::Vector::RobotInterface::SetLCDBrightnessLevel setLCDBrightnessLevel;
    Anki::Vector::RobotInterface::BatteryStatus batteryStatus;
    Anki::Vector::RobotInterface::TriggerBackpackAnimation triggerBackpackAnimation;
    Anki::Vector::RobotInterface::EngineFullyLoaded engineFullyLoaded;
    Anki::Vector::RobotInterface::CheckCloudConnectivity checkCloudConnectivity;
    Anki::Vector::RobotInterface::UpdatedSettings updatedSettings;
  };
  
  EngineToRobot(): tag(INVALID) { }
  
  EngineToRobot( Anki::Vector::RobotInterface::SyncRobot msg ): tag(Tag_syncRobot), syncRobot(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::Shutdown msg ): tag(Tag_shutdown), shutdown(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::CalmPowerMode msg ): tag(Tag_calmPowerMode), calmPowerMode(msg) { }
  EngineToRobot( Anki::Vector::StartControllerTestMode msg ): tag(Tag_startControllerTestMode), startControllerTestMode(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::ControllerGains msg ): tag(Tag_setControllerGains), setControllerGains(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::SetMotionModelParams msg ): tag(Tag_setMotionModelParams), setMotionModelParams(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::RollActionParams msg ): tag(Tag_rollActionParams), rollActionParams(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::PlaypenStart msg ): tag(Tag_playpenStart), playpenStart(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::PrintBodyData msg ): tag(Tag_printBodyData), printBodyData(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::DriveWheels msg ): tag(Tag_drive), drive(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::DriveWheelsCurvature msg ): tag(Tag_driveCurvature), driveCurvature(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::MoveLift msg ): tag(Tag_moveLift), moveLift(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::MoveHead msg ): tag(Tag_moveHead), moveHead(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::SetLiftHeight msg ): tag(Tag_liftHeight), liftHeight(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::SetHeadAngle msg ): tag(Tag_headAngle), headAngle(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::SetLiftAngle msg ): tag(Tag_setLiftAngle), setLiftAngle(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::SetBodyAngle msg ): tag(Tag_setBodyAngle), setBodyAngle(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::TurnInPlaceAtSpeed msg ): tag(Tag_turnInPlaceAtSpeed), turnInPlaceAtSpeed(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::RecordHeading msg ): tag(Tag_recordHeading), recordHeading(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::TurnToRecordedHeading msg ): tag(Tag_turnToRecordedHeading), turnToRecordedHeading(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::EnableMotorPower msg ): tag(Tag_enableMotorPower), enableMotorPower(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::StopAllMotors msg ): tag(Tag_stop), stop(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::BackpackSetLayer msg ): tag(Tag_setBackpackLayer), setBackpackLayer(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::SetBackpackLights msg ): tag(Tag_setBackpackLights), setBackpackLights(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::SetSystemLight msg ): tag(Tag_setSystemLight), setSystemLight(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::ClearPath msg ): tag(Tag_clearPath), clearPath(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::AppendPathSegmentLine msg ): tag(Tag_appendPathSegLine), appendPathSegLine(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::AppendPathSegmentArc msg ): tag(Tag_appendPathSegArc), appendPathSegArc(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::AppendPathSegmentPointTurn msg ): tag(Tag_appendPathSegPointTurn), appendPathSegPointTurn(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::TrimPath msg ): tag(Tag_trimPath), trimPath(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::ExecutePath msg ): tag(Tag_executePath), executePath(msg) { }
  EngineToRobot( Anki::Vector::DockWithObject msg ): tag(Tag_dockWithObject), dockWithObject(msg) { }
  EngineToRobot( Anki::Vector::AbortDocking msg ): tag(Tag_abortDocking), abortDocking(msg) { }
  EngineToRobot( Anki::Vector::PlaceObjectOnGround msg ): tag(Tag_placeObjectOnGround), placeObjectOnGround(msg) { }
  EngineToRobot( Anki::Vector::DockingErrorSignal msg ): tag(Tag_dockingErrorSignal), dockingErrorSignal(msg) { }
  EngineToRobot( Anki::Vector::CarryStateUpdate msg ): tag(Tag_setCarryState), setCarryState(msg) { }
  EngineToRobot( Anki::Vector::CameraFOVInfo msg ): tag(Tag_cameraFOVInfo), cameraFOVInfo(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::AbsoluteLocalizationUpdate msg ): tag(Tag_absLocalizationUpdate), absLocalizationUpdate(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::ForceDelocalizeSimulatedRobot msg ): tag(Tag_forceDelocalizeSimulatedRobot), forceDelocalizeSimulatedRobot(msg) { }
  EngineToRobot( Anki::Vector::IMURequest msg ): tag(Tag_imuRequest), imuRequest(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::CheckLiftLoad msg ): tag(Tag_checkLiftLoad), checkLiftLoad(msg) { }
  EngineToRobot( Anki::Vector::SetCliffDetectThresholds msg ): tag(Tag_setCliffDetectThresholds), setCliffDetectThresholds(msg) { }
  EngineToRobot( Anki::Vector::SetWhiteDetectThresholds msg ): tag(Tag_setWhiteDetectThresholds), setWhiteDetectThresholds(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::StartMotorCalibration msg ): tag(Tag_startMotorCalibration), startMotorCalibration(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::EnableStopOnCliff msg ): tag(Tag_enableStopOnCliff), enableStopOnCliff(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::EnableBraceWhenFalling msg ): tag(Tag_enableBraceWhenFalling), enableBraceWhenFalling(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::RobotStoppedAck msg ): tag(Tag_robotStoppedAck), robotStoppedAck(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::CliffAlignToWhiteAction msg ): tag(Tag_cliffAlignToWhiteAction), cliffAlignToWhiteAction(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::EnableStopOnWhite msg ): tag(Tag_enableStopOnWhite), enableStopOnWhite(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::PlayAnim msg ): tag(Tag_playAnim), playAnim(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::SetFullAnimTrackLockState msg ): tag(Tag_setFullAnimTrackLockState), setFullAnimTrackLockState(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::AddAnim msg ): tag(Tag_addAnim), addAnim(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::AbortAnimation msg ): tag(Tag_abortAnimation), abortAnimation(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::SetLocale msg ): tag(Tag_setLocale), setLocale(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::DrawTextOnScreen msg ): tag(Tag_drawTextOnScreen), drawTextOnScreen(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::DisplayProceduralFace msg ): tag(Tag_displayProceduralFace), displayProceduralFace(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::SetFaceHue msg ): tag(Tag_setFaceHue), setFaceHue(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::SetFaceSaturation msg ): tag(Tag_setFaceSaturation), setFaceSaturation(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::DisplayFaceImageBinaryChunk msg ): tag(Tag_displayFaceImageBinaryChunk), displayFaceImageBinaryChunk(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::DisplayFaceImageRGBChunk msg ): tag(Tag_displayFaceImageRGBChunk), displayFaceImageRGBChunk(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::SetKeepFaceAliveFocus msg ): tag(Tag_setKeepFaceAliveFocus), setKeepFaceAliveFocus(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::EnableKeepFaceAlive msg ): tag(Tag_enableKeepFaceAlive), enableKeepFaceAlive(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::AddOrUpdateEyeShift msg ): tag(Tag_addOrUpdateEyeShift), addOrUpdateEyeShift(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::RemoveEyeShift msg ): tag(Tag_removeEyeShift), removeEyeShift(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::AddSquint msg ): tag(Tag_addSquint), addSquint(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::RemoveSquint msg ): tag(Tag_removeSquint), removeSquint(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::DisplayFaceImageGrayscaleChunk msg ): tag(Tag_displayFaceImageGrayscaleChunk), displayFaceImageGrayscaleChunk(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::PlayAnimWithSpriteBoxRemaps msg ): tag(Tag_playAnimWithSpriteBoxRemaps), playAnimWithSpriteBoxRemaps(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::PlayAnimWithSpriteBoxKeyFrames msg ): tag(Tag_playAnimWithSpriteBoxKeyFrames), playAnimWithSpriteBoxKeyFrames(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::AddSpriteBoxKeyFrames msg ): tag(Tag_addSpriteBoxKeyFrames), addSpriteBoxKeyFrames(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::EnableMirrorModeScreen msg ): tag(Tag_enableMirrorModeScreen), enableMirrorModeScreen(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::SetButtonWakeWord msg ): tag(Tag_setButtonWakeWord), setButtonWakeWord(msg) { }
  EngineToRobot( Anki::AudioEngine::Multiplexer::PostAudioEvent msg ): tag(Tag_postAudioEvent), postAudioEvent(msg) { }
  EngineToRobot( Anki::AudioEngine::Multiplexer::StopAllAudioEvents msg ): tag(Tag_stopAllAudioEvents), stopAllAudioEvents(msg) { }
  EngineToRobot( Anki::AudioEngine::Multiplexer::PostAudioGameState msg ): tag(Tag_postAudioGameState), postAudioGameState(msg) { }
  EngineToRobot( Anki::AudioEngine::Multiplexer::PostAudioSwitchState msg ): tag(Tag_postAudioSwitchState), postAudioSwitchState(msg) { }
  EngineToRobot( Anki::AudioEngine::Multiplexer::PostAudioParameter msg ): tag(Tag_postAudioParameter), postAudioParameter(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::ExternalAudioPrepare msg ): tag(Tag_externalAudioPrepare), externalAudioPrepare(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::ExternalAudioChunk msg ): tag(Tag_externalAudioChunk), externalAudioChunk(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::ExternalAudioComplete msg ): tag(Tag_externalAudioComplete), externalAudioComplete(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::ExternalAudioCancel msg ): tag(Tag_externalAudioCancel), externalAudioCancel(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::FakeWakeWordFromExternalInterface msg ): tag(Tag_fakeWakeWordFromExternalInterface), fakeWakeWordFromExternalInterface(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::ShowUrlFace msg ): tag(Tag_showUrlFace), showUrlFace(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::ExitCCScreen msg ): tag(Tag_exitCCScreen), exitCCScreen(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::SetDebugConsoleVarMessage msg ): tag(Tag_setDebugConsoleVarMessage), setDebugConsoleVarMessage(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::RunDebugConsoleFuncMessage msg ): tag(Tag_runDebugConsoleFuncMessage), runDebugConsoleFuncMessage(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::TextToSpeechPrepare msg ): tag(Tag_textToSpeechPrepare), textToSpeechPrepare(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::TextToSpeechPlay msg ): tag(Tag_textToSpeechPlay), textToSpeechPlay(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::TextToSpeechCancel msg ): tag(Tag_textToSpeechCancel), textToSpeechCancel(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::StartRecordingMicsRaw msg ): tag(Tag_startRecordingMicsRaw), startRecordingMicsRaw(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::StartRecordingMicsProcessed msg ): tag(Tag_startRecordingMicsProcessed), startRecordingMicsProcessed(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::StartPlaybackAudio msg ): tag(Tag_playbackAudioStart), playbackAudioStart(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::StartWakeWordlessStreaming msg ): tag(Tag_startWakeWordlessStreaming), startWakeWordlessStreaming(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::SetTriggerWordResponse msg ): tag(Tag_setTriggerWordResponse), setTriggerWordResponse(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::SetAlexaUXResponses msg ): tag(Tag_setAlexaUXResponses), setAlexaUXResponses(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::ResetBeatDetector msg ): tag(Tag_resetBeatDetector), resetBeatDetector(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::SetAlexaUsage msg ): tag(Tag_setAlexaUsage), setAlexaUsage(msg) { }
  EngineToRobot( Anki::Vector::SwitchboardInterface::SetConnectionStatus msg ): tag(Tag_setConnectionStatus), setConnectionStatus(msg) { }
  EngineToRobot( Anki::Vector::SwitchboardInterface::SetBLEPin msg ): tag(Tag_setBLEPin), setBLEPin(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::AlterStreamingAnimationAtTime msg ): tag(Tag_alterStreamingAnimation), alterStreamingAnimation(msg) { }
  EngineToRobot( Anki::Vector::SwitchboardInterface::SendBLEConnectionStatus msg ): tag(Tag_sendBLEConnectionStatus), sendBLEConnectionStatus(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::SelfTestEnd msg ): tag(Tag_selfTestEnd), selfTestEnd(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::AcousticTestEnabled msg ): tag(Tag_acousticTestEnabled), acousticTestEnabled(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::RangeDataToDisplay msg ): tag(Tag_rangeDataToDisplay), rangeDataToDisplay(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::SetLCDBrightnessLevel msg ): tag(Tag_setLCDBrightnessLevel), setLCDBrightnessLevel(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::BatteryStatus msg ): tag(Tag_batteryStatus), batteryStatus(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::TriggerBackpackAnimation msg ): tag(Tag_triggerBackpackAnimation), triggerBackpackAnimation(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::EngineFullyLoaded msg ): tag(Tag_engineFullyLoaded), engineFullyLoaded(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::CheckCloudConnectivity msg ): tag(Tag_checkCloudConnectivity), checkCloudConnectivity(msg) { }
  EngineToRobot( Anki::Vector::RobotInterface::UpdatedSettings msg ): tag(Tag_updatedSettings), updatedSettings(msg) { }
  /**** Cast to byte buffer, adjusting any padding. ****/
  inline uint8_t* GetBuffer() { return reinterpret_cast<uint8_t*>(&this->tag); }
  inline const uint8_t* GetBuffer() const { return reinterpret_cast<const uint8_t*>(&this->tag); }
  
  /**** Check if current message is parsable. ****/
  bool IsValid() const;
  
  /**** Serialized size, starting from GetBuffer(). ****/
  static const uint32_t MAX_SIZE = 1219;
  static const uint32_t MIN_SIZE = 1;
  uint32_t Size() const;
  
  static const char* TagToString(Tag t);
};

} // namespace RobotInterface

} // namespace Vector

} // namespace Anki

#endif // __CLAD_ROBOT_INTERFACE_MESSAGE_ENGINE_TO_ROBOT_H__
